import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// =========================
// FONT SETUP (UPDATED)
// =========================
const inter = Inter({ subsets: ["latin"] });

// =========================
// METADATA (UNCHANGED)
// =========================
export const metadata: Metadata = {
  title: "OmniFinance | Your Personal Dashboard",
  description: "Generated by create next app",
};

// =========================
// ROOT LAYOUT
// =========================
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-slate-50 text-slate-900`}
      >
        {children}
      </body>
    </html>
  );
}